# Generated by Django 2.0.6 on 2018-10-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procesos',
            new_name='Proceso',
        ),
    ]
