# Generated by Django 2.0.6 on 2018-10-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0002_auto_20181012_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='icono',
            field=models.CharField(blank=True, default='icon-database-insert', max_length=100, null=True),
        ),
    ]
