"""
Django settings for FacturacionElectronica project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ke%t34qe6$u5&uwfcz9@+(cimsm@co5(u5rs)qu%2!$m$bmpv_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FacturacionElectronica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'core.context_processors.menu',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'qr-code': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qr-code-cache',
        'TIMEOUT': 3600
    }
}


WSGI_APPLICATION = 'FacturacionElectronica.wsgi.application'




# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

FILES_JSON = os.path.join(BASE_DIR, "files")

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'franksoto2012@gmail.com'
EMAIL_HOST_PASSWORD = 'MBs0p0rt301'
EMAIL_PORT = 587

RUC= '10452575014'

SUNAT_ARCHIVOS_ROOT = r'\\DESKTOP-ML6FRVL\sunat_archivos\sfs'
SUNAT_DATABASE_ROOT = r'\\DESKTOP-ML6FRVL\bd'

MEDIA_ROOT_FILES =os.path.join(SUNAT_ARCHIVOS_ROOT,'FIRMA')
MEDIA_ROOT_FILES_TXT =os.path.join(SUNAT_ARCHIVOS_ROOT,'DATA')
MEDIA_ROOT_FILES_PDF =os.path.join(SUNAT_ARCHIVOS_ROOT,'REPO')
MEDIA_ROOT_IMG =os.path.join(BASE_DIR, "static","img")
MEDIA_ROOT_FILES_XML_FIRMA =os.path.join(SUNAT_ARCHIVOS_ROOT,'FIRMA')

MEDIA_ROOT_FILES_XML_RPTA =os.path.join(SUNAT_ARCHIVOS_ROOT, 'RPTA')
MEDIA_ROOT_FILES_XML_ENVIO =os.path.join(SUNAT_ARCHIVOS_ROOT,'ENVIO')

QR_CODE_CACHE_ALIAS = 'qr-code'