# Generated by Django 2.0.6 on 2018-10-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, db_column='RUC', max_length=11, null=True)),
                ('razon_social', models.CharField(blank=True, db_column='RAZON_SOCIAL', max_length=100, null=True)),
                ('correo', models.CharField(blank=True, db_column='CORREO', max_length=100, null=True)),
                ('pass_correo', models.CharField(blank=True, db_column='PASS_CORREO', max_length=100, null=True)),
                ('servidor_smtp', models.CharField(blank=True, db_column='SERVIDOR_SMTP', max_length=100, null=True)),
                ('puerto_correo', models.IntegerField(blank=True, db_column='PUERTO_CORREO', null=True)),
                ('logo', models.FileField(blank=True, db_column='LOGO', null=True, upload_to='')),
                ('ruta_archivos_sunat', models.CharField(blank=True, db_column='RUTA_ARCHIVOS_SUNAT', max_length=250, null=True)),
                ('ruta_base_sunat', models.CharField(blank=True, db_column='RUTA_BASE_SUNAT', max_length=250, null=True)),
            ],
            options={
                'db_table': 'EMPRESA_PARAMETRO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=250, null=True)),
                ('otras_referencias', models.CharField(blank=True, max_length=250, null=True)),
                ('serief', models.CharField(blank=True, max_length=10, null=True)),
                ('serieb', models.CharField(blank=True, max_length=10, null=True)),
                ('ncbole', models.CharField(blank=True, max_length=10, null=True)),
                ('ncfact', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_original', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PadronRuc',
            fields=[
                ('ruc', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_razon_social', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('condicion_domicilio', models.CharField(blank=True, max_length=20, null=True)),
                ('ubigeo', models.CharField(blank=True, max_length=6, null=True)),
                ('tipo_via', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_via', models.CharField(blank=True, max_length=250, null=True)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_zona', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('interior', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=250, null=True)),
                ('manzana', models.CharField(blank=True, max_length=50, null=True)),
                ('kilometro', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
