# Generated by Django 2.0.6 on 2018-10-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaparametro',
            options={},
        ),
        migrations.AlterModelTable(
            name='empresaparametro',
            table=None,
        ),
    ]
