# Generated by Django 2.0.6 on 2018-06-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFacturaElectronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codUnidadMedida', models.CharField(max_length=3)),
                ('ctdUnidadItem', models.CharField(max_length=23)),
                ('codProducto', models.CharField(blank=True, max_length=30, null=True)),
                ('codProductoSUNAT', models.CharField(blank=True, max_length=20, null=True)),
                ('desItem', models.CharField(max_length=250)),
                ('mtoValorUnitario', models.CharField(max_length=23)),
                ('mtoDsctoItem', models.CharField(blank=True, max_length=15, null=True)),
                ('mtoIgvItem', models.CharField(max_length=15)),
                ('tipAfeIGV', models.CharField(max_length=2)),
                ('mtoIscItem', models.CharField(blank=True, max_length=15, null=True)),
                ('tipSisISC', models.CharField(blank=True, max_length=2, null=True)),
                ('mtoPrecioVentaItem', models.CharField(max_length=23)),
                ('mtoValorVentaItem', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipOperacion', models.CharField(blank=True, max_length=2, null=True)),
                ('fecEmision', models.CharField(max_length=10)),
                ('codLocalEmisor', models.CharField(blank=True, max_length=3, null=True)),
                ('tipDocUsuario', models.CharField(blank=True, max_length=1, null=True)),
                ('numDocUsuario', models.CharField(blank=True, max_length=15, null=True)),
                ('rznSocialUsuario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipMoneda', models.CharField(max_length=3)),
                ('sumDsctoGlobal', models.CharField(blank=True, max_length=15, null=True)),
                ('sumOtrosCargos', models.CharField(blank=True, max_length=15, null=True)),
                ('mtoDescuentos', models.CharField(blank=True, max_length=15, null=True)),
                ('mtoOperGravadas', models.CharField(max_length=15)),
                ('mtoOperInafectas', models.CharField(max_length=15)),
                ('mtoOperExoneradas', models.CharField(max_length=15)),
                ('mtoIGV', models.CharField(blank=True, max_length=15, null=True)),
                ('mtoISC', models.CharField(blank=True, max_length=15, null=True)),
                ('mtoOtrosTributos', models.CharField(blank=True, max_length=15, null=True)),
                ('mtoImpVenta', models.CharField(max_length=15)),
            ],
        ),
    ]
