# Generated by Django 2.0.6 on 2018-06-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numDocUsuario', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('rznSocialUsuario', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='id',
        ),
        migrations.AddField(
            model_name='detallefacturaelectronica',
            name='numFactura',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='numFactura',
            field=models.CharField(default='000000000001', max_length=25, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
