# Generated by Django 2.0.6 on 2018-07-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantedet',
            name='imp_total_item',
            field=models.DecimalField(blank=True, db_column='IMPORTE_TOTAL_ITEM', decimal_places=2, max_digits=12, null=True),
        ),
    ]
