# Generated by Django 2.0.6 on 2018-07-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_comprobantedet_imp_total_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantedet',
            name='imp_total_item',
            field=models.DecimalField(blank=True, db_column='IMP_TOTAL_ITEM', decimal_places=2, max_digits=12, null=True),
        ),
    ]
