# Generated by Django 2.0.6 on 2018-07-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20180701_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecab',
            name='fec_anula',
            field=models.DateTimeField(blank=True, db_column='FEC_ANULA', null=True),
        ),
        migrations.AddField(
            model_name='comprobantecab',
            name='flg_anula',
            field=models.IntegerField(blank=True, db_column='FLG_ANULA', null=True),
        ),
        migrations.AddField(
            model_name='comprobantecab',
            name='motivo_anula',
            field=models.CharField(blank=True, db_column='MOTIVO_ANULA', max_length=250, null=True),
        ),
    ]
