# Generated by Django 2.0.6 on 2018-06-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20180616_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefacturaelectronica',
            name='numFactura',
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='numFactura',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
