# Generated by Django 2.0.6 on 2018-07-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20180717_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecab',
            name='estado_anula',
            field=models.CharField(blank=True, db_column='ESTADO_ANULA', max_length=250, null=True),
        ),
    ]
