# Generated by Django 2.0.6 on 2018-06-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_auto_20180617_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='numFactura',
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='idComprobante',
            field=models.CharField(default='000010000000001', max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='numComprobante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='serieComprobante',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
