# Generated by Django 2.0.6 on 2018-07-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_auto_20180717_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteBaja',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ruc_emisor', models.CharField(blank=True, db_column='RUC_EMISOR', max_length=11, null=True)),
                ('fecha_doc', models.DateTimeField(blank=True, db_column='FECHA_DOC', null=True)),
                ('tipo_doc', models.CharField(db_column='TIPO_DOC', max_length=2)),
                ('serie_doc', models.CharField(db_column='SERIE_DOC', max_length=4)),
                ('numero_doc', models.CharField(db_column='NUMERO_DOC', max_length=8)),
                ('motivo_baja', models.CharField(blank=True, db_column='MOTIVO_BAJA', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, db_column='ESTADO', max_length=150, null=True)),
                ('usuario', models.CharField(blank=True, db_column='USUARIO', max_length=20, null=True)),
                ('codigopventa', models.CharField(blank=True, db_column='CODIGOPVENTA', max_length=20, null=True)),
            ],
            options={
                'db_table': 'COMPROBANTE_BAJA',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='comprobantebaja',
            unique_together={('tipo_doc', 'serie_doc', 'numero_doc')},
        ),
    ]
