# Generated by Django 2.0.6 on 2018-07-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_auto_20180717_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cfcodcli', models.CharField(db_column='CFCODCLI', max_length=11, primary_key=True, serialize=False)),
                ('cfnombre', models.CharField(blank=True, db_column='CFNOMBRE', max_length=100, null=True)),
                ('direccion_receptor', models.CharField(blank=True, db_column='DIRECCION_RECEPTOR', max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, db_column='CORREO', max_length=200, null=True)),
            ],
            options={
                'db_table': 'CLIENTE',
                'managed': True,
            },
        ),
    ]
