# Generated by Django 2.0.6 on 2018-08-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_auto_20180831_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantecab',
            name='customizacion',
            field=models.CharField(blank=True, db_column='CUSTOMIZACION', max_length=10, null=True),
        ),
    ]
