# Generated by Django 2.0.6 on 2018-09-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_comprobantecab_customizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo05TiposTributos',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=6, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('un_ece_5153', models.CharField(blank=True, db_column='UN_ECE_5153', max_length=3, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_05_TIPOS_TRIBUTOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogo15ElementosAdicionales',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=4, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_15_ELEMENTOS_ADICIONALES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumenCab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raz_social_emisor', models.CharField(blank=True, db_column='RAZ_SOCIAL_EMISOR', max_length=100, null=True)),
                ('ruc_emisor', models.CharField(blank=True, db_column='RUC_EMISOR', max_length=11, null=True)),
                ('tip_doc_emisor', models.CharField(blank=True, db_column='TIP_DOC_EMISOR', max_length=1, null=True)),
                ('fec_doc', models.DateTimeField(blank=True, db_column='FEC_DOC', null=True)),
                ('tipo_resumen', models.CharField(blank=True, db_column='TIPO_RESUMEN', max_length=2, null=True)),
                ('numdoc_resumen', models.CharField(db_column='NUMDOC_RESUMEN', max_length=5)),
                ('fecha_gen', models.DateTimeField(blank=True, db_column='FECHA_GEN', null=True)),
                ('ubl_version', models.CharField(blank=True, db_column='UBL_VERSION', max_length=10, null=True)),
                ('estruc_version', models.CharField(blank=True, db_column='ESTRUC_VERSION', max_length=10, null=True)),
                ('estado_resumen', models.CharField(blank=True, db_column='ESTADO_RESUMEN', max_length=150, null=True)),
                ('cdr', models.CharField(blank=True, db_column='CDR', max_length=50, null=True)),
                ('ruta_comprobante', models.CharField(blank=True, db_column='RUTA_RESUMEN', max_length=4000, null=True)),
                ('ruta_cdr', models.CharField(blank=True, db_column='RUTA_CDR', max_length=4000, null=True)),
                ('tipo_envio', models.CharField(blank=True, db_column='TIPO_ENVIO', max_length=10, null=True)),
                ('ticket', models.CharField(blank=True, db_column='TICKET', max_length=50, null=True)),
                ('xml', models.TextField(blank=True, db_column='XML', null=True)),
            ],
            options={
                'db_table': 'RESUMEN_CAB',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResumenDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodoc_item', models.CharField(blank=True, db_column='TIPODOC_ITEM', max_length=2, null=True)),
                ('numserie_item', models.CharField(blank=True, db_column='NUMSERIE_ITEM', max_length=4, null=True)),
                ('numdoc_item', models.CharField(db_column='NUMDOC_ITEM', max_length=8)),
                ('tipdoc_receptor', models.CharField(blank=True, db_column='TIPDOC_RECEPTOR', max_length=1, null=True)),
                ('nrodoc_receptor', models.CharField(blank=True, db_column='NRODOC_RECEPTOR', max_length=15, null=True)),
                ('moneda', models.CharField(blank=True, db_column='MONEDA', max_length=3, null=True)),
                ('tvv_imp_ope_gravadas', models.DecimalField(db_column='TVV_IMP_OPE_GRAVADAS', decimal_places=2, max_digits=12)),
                ('tvv_cod_ope_gravadas', models.CharField(blank=True, db_column='TVV_COD_OPE_GRAVADAS', max_length=2, null=True)),
                ('tvv_imp_ope_inafectas', models.DecimalField(db_column='TVV_IMP_OPE_INAFECTAS', decimal_places=2, max_digits=12)),
                ('tvv_cod_ope_inafectas', models.CharField(blank=True, db_column='TVV_COD_OPE_INAFECTAS', max_length=2, null=True)),
                ('tvv_imp_ope_exoneradas', models.DecimalField(db_column='TVV_IMP_OPE_EXONERADAS', decimal_places=2, max_digits=12)),
                ('tvv_cod_ope_exoneradas', models.CharField(blank=True, db_column='TVV_COD_OPE_EXONERADAS', max_length=2, null=True)),
                ('tvv_imp_ope_gratuitas', models.DecimalField(db_column='TVV_IMP_OPE_GRATUITAS', decimal_places=2, max_digits=12)),
                ('tvv_cod_ope_gratuitas', models.CharField(blank=True, db_column='TVV_COD_OPE_GRATUITAS', max_length=2, null=True)),
                ('imp_total_sum_otros_cargos', models.DecimalField(db_column='IMP_TOTAL_SUM_OTROS_CARGOS', decimal_places=2, max_digits=12)),
                ('cod_tip_otros_cargos', models.CharField(blank=True, db_column='COD_TIP_OTROS_CARGOS', max_length=5, null=True)),
                ('monto_isc', models.DecimalField(db_column='MONTO_ISC', decimal_places=2, max_digits=12)),
                ('cod_tributo_isc', models.CharField(blank=True, db_column='COD_TRIBUTO_ISC', max_length=4, null=True)),
                ('nom_tributo_isc', models.CharField(blank=True, db_column='NOM_TRIBUTO_ISC', max_length=10, null=True)),
                ('cod_inter_isc', models.CharField(blank=True, db_column='COD_INTER_ISC', max_length=3, null=True)),
                ('monto_igv', models.DecimalField(db_column='MONTO_IGV', decimal_places=2, max_digits=12)),
                ('cod_tributo_igv', models.CharField(blank=True, db_column='COD_TRIBUTO_IGV', max_length=4, null=True)),
                ('nom_tributo_igv', models.CharField(blank=True, db_column='NOM_TRIBUTO_IGV', max_length=10, null=True)),
                ('cod_inter_igv', models.CharField(blank=True, db_column='COD_INTER_IGV', max_length=3, null=True)),
                ('monto_otros_trib', models.DecimalField(db_column='MONTO_OTROS_TRIB', decimal_places=2, max_digits=12)),
                ('cod_tributo_otros_trib', models.CharField(blank=True, db_column='COD_TRIBUTO_OTROS_TRIB', max_length=4, null=True)),
                ('nom_tributo_otros_trib', models.CharField(blank=True, db_column='NOM_TRIBUTO_OTROS_TRIB', max_length=10, null=True)),
                ('cod_inter_otros_trib', models.CharField(blank=True, db_column='COD_INTER_OTROS_TRIB', max_length=3, null=True)),
                ('importe_total_venta', models.DecimalField(db_column='IMPORTE_TOTAL_VENTA', decimal_places=2, max_digits=12)),
                ('tipodoc_modif', models.CharField(blank=True, db_column='TIPODOC_MODIF', max_length=2, null=True)),
                ('numserie_modif', models.CharField(blank=True, db_column='NUMSERIE_MODIF', max_length=2, null=True)),
                ('numdoc_modif', models.CharField(blank=True, db_column='NUMDOC_MODIF', max_length=2, null=True)),
                ('regimen_percepcion', models.CharField(blank=True, db_column='REGIMEN_PERCEPCION', max_length=2, null=True)),
                ('porcent_percepcion', models.DecimalField(blank=True, db_column='PORCENT_PERCEPCION', decimal_places=2, max_digits=12, null=True)),
                ('base_imponible_percepcion', models.DecimalField(blank=True, db_column='BASE_IMPONIBLE_PERCEPCION', decimal_places=2, max_digits=12, null=True)),
                ('monto_percepcion', models.DecimalField(blank=True, db_column='MONTO_PERCEPCION', decimal_places=2, max_digits=12, null=True)),
                ('motivo_baja', models.CharField(blank=True, db_column='MOTIVO_BAJA', max_length=100, null=True)),
                ('orden_item', models.CharField(blank=True, db_column='ORDEN_ITEM', max_length=5, null=True)),
                ('tipo_resumen', models.CharField(blank=True, db_column='TIPO_RESUMEN', max_length=2, null=True)),
                ('numdoc_resumen', models.CharField(blank=True, db_column='NUMDOC_RESUMEN', max_length=5, null=True)),
                ('estado', models.CharField(blank=True, db_column='ESTADO', max_length=2, null=True)),
                ('resumen_cab', models.ForeignKey(blank=True, null=True, on_delete=False, to='facturacion.ResumenCab')),
            ],
            options={
                'db_table': 'RESUMEN_DET',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='comprobantedet',
            name='porcent_igv',
            field=models.DecimalField(blank=True, db_column='PORCENT_IGV', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='comprobantedet',
            name='porcent_isc',
            field=models.DecimalField(blank=True, db_column='PORCENT_ISC', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resumencab',
            unique_together={('tipo_resumen', 'numdoc_resumen')},
        ),
    ]
