# Generated by Django 2.0.6 on 2018-09-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_auto_20180902_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumencab',
            name='numdoc_resumen',
            field=models.CharField(db_column='NUMDOC_RESUMEN', max_length=15),
        ),
        migrations.AlterField(
            model_name='resumendet',
            name='numdoc_modif',
            field=models.CharField(blank=True, db_column='NUMDOC_MODIF', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='resumendet',
            name='numdoc_resumen',
            field=models.CharField(blank=True, db_column='NUMDOC_RESUMEN', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resumendet',
            name='numserie_modif',
            field=models.CharField(blank=True, db_column='NUMSERIE_MODIF', max_length=4, null=True),
        ),
    ]
