# Generated by Django 2.0.6 on 2018-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_auto_20180902_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumendet',
            name='ruc_emisor',
            field=models.CharField(blank=True, db_column='RUC_EMISOR', max_length=11, null=True),
        ),
    ]
