# Generated by Django 2.0.6 on 2018-09-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_ejemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ejemplo',
        ),
    ]
