# Generated by Django 2.0.6 on 2018-09-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_delete_ejemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDocumentoSunat',
            fields=[
                ('id', models.CharField(db_column='id', max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='nombre', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ESTADO_DOCUMENTO_SUNAT',
                'managed': True,
            },
        ),
    ]
