# Generated by Django 2.0.6 on 2018-09-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_auto_20180902_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumencab',
            name='estado_resumen',
            field=models.ForeignKey(blank=True, max_length=5, null=True, on_delete=False, to='facturacion.EstadoDocumento'),
        ),
    ]
