# Generated by Django 2.0.6 on 2018-09-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_auto_20180903_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumencab',
            name='numser_resumen',
            field=models.CharField(blank=True, db_column='NUMSER_RESUMEN', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='resumendet',
            name='numser_resumen',
            field=models.CharField(blank=True, db_column='NUMSER_RESUMEN', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='resumencab',
            name='numdoc_resumen',
            field=models.CharField(blank=True, db_column='NUMDOC_RESUMEN', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='resumencab',
            name='tipo_resumen',
            field=models.CharField(blank=True, choices=[('RC', 'RESUMEN DE COMPROBANTE'), ('RA', 'RESUMEN DE ANULACION')], db_column='TIPO_RESUMEN', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='resumendet',
            name='numdoc_resumen',
            field=models.CharField(blank=True, db_column='NUMDOC_RESUMEN', max_length=3, null=True),
        ),
    ]
