# Generated by Django 2.0.6 on 2018-09-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0020_auto_20180903_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumendet',
            name='fecdoc_item',
            field=models.CharField(blank=True, db_column='FECDOC_ITEM', max_length=2, null=True),
        ),
    ]
