# Generated by Django 2.0.6 on 2018-09-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0021_resumendet_fecdoc_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumendet',
            name='fecdoc_item',
            field=models.DateTimeField(blank=True, db_column='FECDOC_ITEM', null=True),
        ),
    ]
