# Generated by Django 2.0.6 on 2018-09-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_auto_20180903_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecab',
            name='estado_comprobante',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=False, to='facturacion.EstadoDocumento'),
        ),
    ]
