# Generated by Django 2.0.6 on 2018-09-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0029_resumencab_nro_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo01TipoDocumento',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('un_1001', models.CharField(blank=True, db_column='UN_1001', max_length=3, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_01_TIPO_DOCUMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Catalogo06DocumentoIdentidad',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_06_DOCUMENTO_IDENTIDAD',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='comprobantecab',
            name='tip_doc_emisor',
            field=models.ForeignKey(blank=True, db_column='TIP_DOC_EMISOR', db_constraint=False, max_length=1, null=True, on_delete=False, to='facturacion.Catalogo06DocumentoIdentidad'),
        ),
        migrations.AlterField(
            model_name='comprobantecab',
            name='tipodoc_comprobante',
            field=models.ForeignKey(blank=True, db_column='TIPODOC_COMPROBANTE', db_constraint=False, max_length=2, null=True, on_delete=False, to='facturacion.Catalogo01TipoDocumento'),
        ),
        migrations.AlterField(
            model_name='resumendet',
            name='tipodoc_item',
            field=models.ForeignKey(blank=True, db_column='TIPODOC_ITEM', db_constraint=False, max_length=2, null=True, on_delete=False, to='facturacion.Catalogo01TipoDocumento'),
        ),
    ]
