# Generated by Django 2.0.6 on 2018-09-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0030_auto_20180909_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumendet',
            name='tipdoc_receptor',
            field=models.ForeignKey(blank=True, db_column='TIPDOC_RECEPTOR', db_constraint=False, max_length=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.Catalogo06DocumentoIdentidad'),
        ),
        migrations.AlterField(
            model_name='resumendet',
            name='tipodoc_item',
            field=models.ForeignKey(blank=True, db_column='TIPODOC_ITEM', db_constraint=False, max_length=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='facturacion.Catalogo01TipoDocumento'),
        ),
    ]
