# Generated by Django 2.0.6 on 2018-09-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0031_auto_20180909_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumencab',
            name='nro_reg',
            field=models.IntegerField(blank=True, db_column='NRO_REG', default=0, null=True),
        ),
    ]
