# Generated by Django 2.0.6 on 2018-09-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0032_auto_20180909_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumendet',
            name='tvv_cod_ope_exoneradas',
            field=models.CharField(blank=True, db_column='TVV_COD_OPE_EXONERADAS', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='resumendet',
            name='tvv_cod_ope_gratuitas',
            field=models.CharField(blank=True, db_column='TVV_COD_OPE_GRATUITAS', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='resumendet',
            name='tvv_cod_ope_gravadas',
            field=models.CharField(blank=True, db_column='TVV_COD_OPE_GRAVADAS', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='resumendet',
            name='tvv_cod_ope_inafectas',
            field=models.CharField(blank=True, db_column='TVV_COD_OPE_INAFECTAS', max_length=4, null=True),
        ),
    ]
