# Generated by Django 2.0.6 on 2018-09-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0033_auto_20180912_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumencab',
            name='tipo',
            field=models.CharField(blank=True, db_column='TIPO', max_length=2, null=True),
        ),
    ]
