# Generated by Django 2.0.6 on 2018-09-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0035_auto_20180918_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantecab',
            name='cfnombre',
            field=models.CharField(blank=True, db_column='CFNOMBRE', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantecab',
            name='direccion_emisor',
            field=models.CharField(blank=True, db_column='DIRECCION_EMISOR', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantecab',
            name='direccion_receptor',
            field=models.CharField(blank=True, db_column='DIRECCION_RECEPTOR', max_length=250, null=True),
        ),
    ]
