# Generated by Django 2.0.6 on 2018-10-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0036_auto_20180918_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, db_column='RUC', max_length=11, null=True)),
                ('razon_social', models.CharField(blank=True, db_column='RAZON_SOCIAL', max_length=100, null=True)),
                ('correo', models.CharField(blank=True, db_column='CORREO', max_length=100, null=True)),
                ('pass_correo', models.CharField(blank=True, db_column='PASS_CORREO', max_length=100, null=True)),
                ('servidor_smtp', models.CharField(blank=True, db_column='SERVIDOR_SMTP', max_length=100, null=True)),
                ('puerto_correo', models.IntegerField(blank=True, db_column='PUERTO_CORREO', null=True)),
                ('logo', models.FileField(blank=True, db_column='LOGO', null=True, upload_to='')),
                ('ruta_archivos_sunat', models.CharField(blank=True, db_column='RUTA_ARCHIVOS_SUNAT', max_length=250, null=True)),
                ('ruta_base_sunat', models.CharField(blank=True, db_column='RUTA_BASE_SUNAT', max_length=250, null=True)),
            ],
        ),
    ]
