# Generated by Django 2.0.6 on 2018-10-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0037_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('codigo', models.CharField(db_column='CODIGO', max_length=3, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=100, null=True)),
            ],
        ),
    ]
