# Generated by Django 2.0.6 on 2018-10-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0039_auto_20181007_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpresaParametro',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
    ]
