# Generated by Django 2.0.6 on 2018-07-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_auto_20180723_2215'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='modulos.Permiso'),
        ),
    ]
