# Generated by Django 2.0.6 on 2018-07-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_auto_20180723_2215'),
        ('usuarios', '0002_usuario_permiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='permiso',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='modulos.Rol'),
        ),
    ]
