# Generated by Django 2.0.6 on 2018-07-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='requiere_autenticacion',
            field=models.BooleanField(default=True),
        ),
    ]
