# Generated by Django 2.0.6 on 2018-07-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_menu_requiere_autenticacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=False, to='modulos.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='permisos',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='modulos.Rol'),
        ),
    ]
